### ISSUE TITLE
I install slardar and run nginx but got this

### ISSUE THREAD

**Issue by towtooth** [upyun/slardar#24]
nginx: [error] stream [lua] api.lua:30: get_kv_blocking(): get config from http://127.0.0.1:8500/v1/kv/config/slardar/stream_upstreams?keys failed
nginx: [error] init_by_lua_file error: /usr/local/slardar/nginx/app/src/stream/init.lua:13: Init config failed, aborting !!!!
stack traceback:
	[C]: in function 'error'
	/usr/local/slardar/nginx/app/src/stream/init.lua:13: in main chunk

how can i fix this?

**Comment by yejingx** [comment]
> how can i fix this?

Is your consul running and working properly?

**Comment by towtooth** [comment]
No,seems like consul init failed but don't know why.Does not consul run with  run nginx?

**Comment by towtooth** [comment]
em, should i install consul...

**Comment by towtooth** [comment]
em,i did't install consul,sry
