### ISSUE TITLE
Can't find variable

### ISSUE THREAD

**Issue by liyuepeng1991** [upyun/slardar#3]
Hi! I have a issue when i read the file :lib/resty/checkups/base.lua , in this file, i couldn't find the upstream.checkups[] where it defineded. Can you help me? thankyou!
我在lib/resty/checkups/base.lua这个文件中找不到upstream.checkups[]的定义和声明，好像直接就开始使用了，不太理解，可否帮忙告知，谢谢

**Comment by yejingx** [comment]
`upstream.checkups` is initialized [here](https://github.com/upyun/slardar/blob/master/nginx/app/lib/resty/checkups/api.lua#L135).

**Comment by liyuepeng1991** [comment]
Get it!thankyou
